[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic_float = "0.1.0"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
rand = "0.8.5"
rayon = "1.7.0"
